%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
# dataset_dir: /media/xiang/Data/Dataset/Kitti/dataset/sequences/00
dataset_dir: /home/brave/Desktop/kitti00/kitti00/dataset/sequences/00

# camera intrinsics
camera.fx: 718.856
camera.fy: 718.856
camera.cx: 687.1928
camera.cy: 185.2157

num_features: 50
num_features_init: 100
num_features_tracking: 50

## 参数配置
# 内外点比例阈值
chi2_th: 5.991
# 相邻最近关键帧的最大距离
min_dis_th: 0.2


## 方法配置
# 保存轨迹文件
is_save_trajectory: true
save_dir: /home/brave/Desktop/output
trajectory_file_name: "trajectory.txt"

## 特征提取方法
#capture_feature_function: "GFTT"

# 建图 全局 or 局部
update_map_all: true

# 回环文件名字
loop_model_name: "model.yml.gz"