%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
# dataset_dir: /media/xiang/Data/Dataset/Kitti/dataset/sequences/00
dataset_dir: /home/brave/Desktop/kitti00/kitti00/dataset/sequences/00

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

num_features: 150
num_features_init: 50
num_features_tracking: 50

## 参数配置
# 内外点比例阈值
chi2_th: 5.991
# 相邻最近关键帧的最大距离
min_dis_th: 0.2

## 方法配置
# 保存轨迹文件
is_save_trajectory: true
save_dir: /home/brave/Desktop/output
trajectory_file_name: "trajectory.txt"


